season: 2026
players:
- name: 森下龍矢
  tm: '679903'
  club: Blackburn Rovers
  club_en: Blackburn Rovers
  club_id: '164'
  competition: GB2
  position: Midfielder
  dob: '1997-04-11'
  games: 10
  played: 10
  starts: 10
  minutes: 860
  goals: 2
  assists: 2
  grade: null
  bench: 0
  injured: 0
- name: 小久保玲央ブライアン
  tm: '501737'
  club: Sint-Truidense VV
  club_en: Sint-Truidense VV
  club_id: '475'
  competition: BE1
  position: Goalkeeper
  dob: '2001-01-23'
  games: 9
  played: 9
  starts: 9
  minutes: 810
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 岩田智輝
  tm: '356236'
  club: Birmingham City
  club_en: Birmingham City
  club_id: '337'
  competition: GB2
  position: Midfielder
  dob: '1997-04-07'
  games: 10
  played: 10
  starts: 9
  minutes: 809
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 松木玖生
  tm: '902021'
  club: Southampton FC
  club_en: Southampton FC
  club_id: '180'
  competition: GB2
  position: Midfielder
  dob: '2003-04-30'
  games: 10
  played: 10
  starts: 7
  minutes: 669
  goals: 1
  assists: 1
  grade: null
  bench: 0
  injured: 0
- name: 木村誠二
  tm: '501749'
  club: KVC Westerlo
  club_en: KVC Westerlo
  club_id: '968'
  competition: BE1
  position: Defender
  dob: '2001-08-24'
  games: 7
  played: 7
  starts: 7
  minutes: 630
  goals: 0
  assists: 1
  grade: null
  bench: 0
  injured: 0
- name: 三好康児
  tm: '295060'
  club: VfL Bochum
  club_en: VfL Bochum
  club_id: '80'
  competition: L2
  position: Midfielder
  dob: '1997-03-26'
  games: 7
  played: 7
  starts: 7
  minutes: 605
  goals: 2
  assists: 1
  grade: 3.27
  bench: 0
  injured: 0
- name: 伊東純也
  tm: '348791'
  club: KRC Genk
  club_en: KRC Genk
  club_id: '1184'
  competition: BE1
  position: Striker
  dob: '1993-03-09'
  games: 7
  played: 7
  starts: 7
  minutes: 587
  goals: 1
  assists: 2
  grade: null
  bench: 0
  injured: 0
- name: 渡辺剛
  tm: '598791'
  club: フェイエノールト
  club_en: Feyenoord Rotterdam
  club_id: '234'
  competition: NL1
  position: Defender
  dob: '1997-02-05'
  games: 8
  played: 7
  starts: 7
  minutes: 581
  goals: 0
  assists: 1
  grade: null
  bench: 0
  injured: 1
- name: 上田綺世
  tm: '589128'
  club: LOSC Lille
  club_en: LOSC Lille
  club_id: '1082'
  competition: FR1
  position: Striker
  dob: '1998-08-28'
  games: 8
  played: 8
  starts: 7
  minutes: 579
  goals: 6
  assists: 1
  grade: null
  bench: 0
  injured: 0
- name: 佐野航大
  tm: '957544'
  club: PSV
  club_en: PSV Eindhoven
  club_id: '383'
  competition: NL1
  position: Midfielder
  dob: '2003-09-25'
  games: 9
  played: 7
  starts: 6
  minutes: 567
  goals: 1
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 鎌田大地
  tm: '356141'
  club: クリスタル・パレス
  club_en: Crystal Palace
  club_id: '873'
  competition: GB1
  position: Midfielder
  dob: '1996-08-05'
  games: 7
  played: 7
  starts: 6
  minutes: 548
  goals: 1
  assists: 3
  grade: null
  bench: 0
  injured: 0
- name: 鈴木唯人
  tm: '668606'
  club: SC Freiburg
  club_en: SC Freiburg
  club_id: '60'
  competition: L1
  position: Striker
  dob: '2001-10-25'
  games: 7
  played: 7
  starts: 7
  minutes: 530
  goals: 4
  assists: 0
  grade: 2.35
  bench: 0
  injured: 0
- name: 山本天翔
  tm: '1385085'
  club: ドルトムント
  club_en: Borussia Dortmund
  club_id: '16'
  competition: L1
  position: Midfielder
  dob: '2007-08-24'
  games: 11
  played: 8
  starts: 5
  minutes: 529
  goals: 0
  assists: 3
  grade: null
  bench: 0
  injured: 0
- name: 鈴木彩艶
  tm: '432298'
  club: アストン・ヴィラ
  club_en: Aston Villa
  club_id: '405'
  competition: GB1
  position: Goalkeeper
  dob: '2002-08-21'
  games: 8
  played: 6
  starts: 5
  minutes: 495
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 安藤智哉
  tm: '610795'
  club: FC St. Pauli
  club_en: FC St. Pauli
  club_id: '35'
  competition: L2
  position: Defender
  dob: '1999-01-10'
  games: 7
  played: 6
  starts: 6
  minutes: 471
  goals: 0
  assists: 0
  grade: 4.1
  bench: 0
  injured: 0
- name: ハーフナーニッキ
  tm: '129684'
  club: Union Saint-Gilloise
  club_en: Union Saint-Gilloise
  club_id: '3948'
  competition: BE1
  position: Defender
  dob: '1995-02-16'
  games: 11
  played: 8
  starts: 4
  minutes: 460
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 小杉啓太
  tm: '1146988'
  club: フランクフルト
  club_en: Eintracht Frankfurt
  club_id: '24'
  competition: L1
  position: Defender
  dob: '2006-03-18'
  games: 5
  played: 5
  starts: 5
  minutes: 450
  goals: 0
  assists: 3
  grade: 3.77
  bench: 0
  injured: 0
- name: 瀬古歩夢
  tm: '405389'
  club: Le Havre AC
  club_en: Le Havre AC
  club_id: '738'
  competition: FR1
  position: Defender
  dob: '2000-06-07'
  games: 5
  played: 5
  starts: 5
  minutes: 450
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 佐野海舟
  tm: '643574'
  club: 1.FSV Mainz 05
  club_en: 1.FSV Mainz 05
  club_id: '39'
  competition: L1
  position: Midfielder
  dob: '2000-12-30'
  games: 5
  played: 5
  starts: 5
  minutes: 448
  goals: 0
  assists: 2
  grade: 2.97
  bench: 0
  injured: 0
- name: アペルカンプ真大
  tm: '452121'
  club: SpVgg Greuther Fürth
  club_en: SpVgg Greuther Fürth
  club_id: '65'
  competition: L2
  position: Midfielder
  dob: '2000-11-01'
  games: 7
  played: 5
  starts: 5
  minutes: 417
  goals: 0
  assists: 1
  grade: 3.13
  bench: 0
  injured: 2
- name: 谷口彰悟
  tm: '307870'
  club: Sint-Truidense VV
  club_en: Sint-Truidense VV
  club_id: '475'
  competition: BE1
  position: Defender
  dob: '1991-07-15'
  games: 9
  played: 6
  starts: 5
  minutes: 408
  goals: 1
  assists: 0
  grade: null
  bench: 0
  injured: 1
- name: 板倉滉
  tm: '355816'
  club: Ajax Amsterdam
  club_en: Ajax Amsterdam
  club_id: '610'
  competition: NL1
  position: Defender
  dob: '1997-01-27'
  games: 11
  played: 5
  starts: 4
  minutes: 387
  goals: 0
  assists: 0
  grade: 4.78
  bench: 0
  injured: 5
- name: 原大智
  tm: '495752'
  club: FC St. Pauli
  club_en: FC St. Pauli
  club_id: '35'
  competition: L2
  position: Striker
  dob: '1999-05-05'
  games: 7
  played: 7
  starts: 5
  minutes: 378
  goals: 2
  assists: 1
  grade: 3.32
  bench: 0
  injured: 0
- name: 藤田譲瑠チマ
  tm: '697277'
  club: FC St. Pauli
  club_en: FC St. Pauli
  club_id: '35'
  competition: L2
  position: Midfielder
  dob: '2002-02-16'
  games: 7
  played: 5
  starts: 5
  minutes: 378
  goals: 1
  assists: 0
  grade: 2.94
  bench: 0
  injured: 0
- name: 田中碧
  tm: '489359'
  club: リーズ
  club_en: Leeds United
  club_id: '399'
  competition: GB1
  position: Midfielder
  dob: '1998-09-10'
  games: 7
  played: 6
  starts: 4
  minutes: 348
  goals: 0
  assists: 2
  grade: null
  bench: 0
  injured: 0
- name: 塩貝健人
  tm: '1144627'
  club: VfL Wolfsburg
  club_en: VfL Wolfsburg
  club_id: '82'
  competition: L2
  position: Striker
  dob: '2005-03-26'
  games: 7
  played: 6
  starts: 3
  minutes: 336
  goals: 0
  assists: 0
  grade: 3.95
  bench: 0
  injured: 0
- name: 佐藤龍之介
  tm: '948169'
  club: バレンシア
  club_en: Valencia CF
  club_id: '1049'
  competition: ES1
  position: Striker
  dob: '2006-10-16'
  games: 7
  played: 5
  starts: 4
  minutes: 297
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 冨安健洋
  tm: '331560'
  club: クリスタル・パレス
  club_en: Crystal Palace
  club_id: '873'
  competition: GB1
  position: Defender
  dob: '1998-11-05'
  games: 7
  played: 5
  starts: 3
  minutes: 280
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 前田大然
  tm: '420931'
  club: イプスウィッチ
  club_en: Ipswich Town
  club_id: '677'
  competition: GB1
  position: Striker
  dob: '1997-10-20'
  games: 7
  played: 6
  starts: 3
  minutes: 271
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 堂安律
  tm: '358504'
  club: フランクフルト
  club_en: Eintracht Frankfurt
  club_id: '24'
  competition: L1
  position: Striker
  dob: '1998-06-16'
  games: 5
  played: 3
  starts: 3
  minutes: 238
  goals: 0
  assists: 1
  grade: 3.31
  bench: 0
  injured: 2
- name: 久保建英
  tm: '405398'
  club: レアル・ソシエダ
  club_en: Real Sociedad
  club_id: '681'
  competition: ES1
  position: Striker
  dob: '2001-06-04'
  games: 8
  played: 6
  starts: 3
  minutes: 230
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 旗手怜央
  tm: '496656'
  club: Celtic FC
  club_en: Celtic FC
  club_id: '371'
  competition: SC1
  position: Midfielder
  dob: '1997-11-21'
  games: 11
  played: 6
  starts: 2
  minutes: 226
  goals: 0
  assists: 1
  grade: null
  bench: 0
  injured: 0
- name: 町田浩樹
  tm: '415035'
  club: TSG 1899 Hoffenheim
  club_en: TSG 1899 Hoffenheim
  club_id: '533'
  competition: L1
  position: Defender
  dob: '1997-08-25'
  games: 7
  played: 4
  starts: 2
  minutes: 201
  goals: 0
  assists: 0
  grade: 3.91
  bench: 0
  injured: 0
- name: 山田新
  tm: '681970'
  club: Oud-Heverlee Leuven
  club_en: Oud-Heverlee Leuven
  club_id: '2727'
  competition: BE1
  position: Striker
  dob: '2000-05-30'
  games: 7
  played: 6
  starts: 2
  minutes: 192
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 橋岡大樹
  tm: '387191'
  club: ボルシアMG
  club_en: Borussia Mönchengladbach
  club_id: '18'
  competition: L1
  position: Defender
  dob: '1999-05-17'
  games: 6
  played: 3
  starts: 2
  minutes: 180
  goals: 1
  assists: 0
  grade: 4.43
  bench: 0
  injured: 2
- name: 坂元達裕
  tm: '617408'
  club: コヴェントリー
  club_en: Coventry City
  club_id: '990'
  competition: GB1
  position: Midfielder
  dob: '1996-10-22'
  games: 7
  played: 3
  starts: 2
  minutes: 178
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 中村敬斗
  tm: '405397'
  club: Olympique Lyon
  club_en: Olympique Lyon
  club_id: '1041'
  competition: FR1
  position: Striker
  dob: '2000-07-28'
  games: 8
  played: 3
  starts: 1
  minutes: 116
  goals: 1
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 大橋祐紀
  tm: '592116'
  club: Blackburn Rovers
  club_en: Blackburn Rovers
  club_id: '164'
  competition: GB2
  position: Striker
  dob: '1996-07-27'
  games: 10
  played: 4
  starts: 2
  minutes: 116
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 新川志音
  tm: '1153358'
  club: Sint-Truidense VV
  club_en: Sint-Truidense VV
  club_id: '475'
  competition: BE1
  position: Striker
  dob: '2007-08-06'
  games: 10
  played: 5
  starts: 1
  minutes: 111
  goals: 1
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 高橋仁胡
  tm: '834465'
  club: Holstein Kiel
  club_en: Holstein Kiel
  club_id: '269'
  competition: L2
  position: Defender
  dob: '2005-08-17'
  games: 7
  played: 2
  starts: 1
  minutes: 78
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 守田英正
  tm: '524315'
  club: ハル・シティ
  club_en: Hull City
  club_id: '3008'
  competition: GB1
  position: Midfielder
  dob: '1995-05-10'
  games: 7
  played: 2
  starts: 1
  minutes: 76
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 毎熊晟矢
  tm: '733438'
  club: AZ Alkmaar
  club_en: AZ Alkmaar
  club_id: '1090'
  competition: NL1
  position: Defender
  dob: '1997-10-16'
  games: 9
  played: 6
  starts: 0
  minutes: 64
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 菅原由勢
  tm: '405385'
  club: Southampton FC
  club_en: Southampton FC
  club_id: '180'
  competition: GB2
  position: Defender
  dob: '2000-06-28'
  games: 9
  played: 2
  starts: 0
  minutes: 53
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 伊藤洋輝
  tm: '353892'
  club: バイエルン
  club_en: Bayern Munich
  club_id: '27'
  competition: L1
  position: Defender
  dob: '1999-05-12'
  games: 7
  played: 1
  starts: 0
  minutes: 10
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 遠藤航
  tm: '146310'
  club: リバプール
  club_en: Liverpool FC
  club_id: '31'
  competition: GB1
  position: Midfielder
  dob: '1993-02-09'
  games: 7
  played: 0
  starts: 0
  minutes: 0
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
- name: 南野拓実
  tm: '165793'
  club: モナコ
  club_en: AS Monaco
  club_id: '162'
  competition: FR1
  position: Striker
  dob: '1995-01-16'
  games: 7
  played: 0
  starts: 0
  minutes: 0
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 6
- name: 三笘薫
  tm: '504849'
  club: ブライトン
  club_en: Brighton & Hove Albion
  club_id: '1237'
  competition: GB1
  position: Striker
  dob: '1997-05-20'
  games: 8
  played: 0
  starts: 0
  minutes: 0
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 8
- name: 高井幸大
  tm: '671108'
  club: Sint-Truidense VV
  club_en: Sint-Truidense VV
  club_id: '475'
  competition: BE1
  position: Defender
  dob: '2004-09-04'
  games: 7
  played: 0
  starts: 0
  minutes: 0
  goals: 0
  assists: 0
  grade: null
  bench: 0
  injured: 0
