import '../models/attributes.dart';

/// 局面の選択がうまくいったときに何が起きるか。
enum Outcome {
  /// ゴール。
  goal,

  /// アシスト。
  assist,

  /// 得点には直結しないが、評価される良いプレー。
  play,
}

/// 局面で選べる1つの手。
class ScenarioOption {
  const ScenarioOption({
    required this.label,
    required this.key,
    this.detail,
    required this.difficulty,
    required this.outcome,
    required this.successText,
    required this.failureText,
  });

  final String label;

  /// 成否を判定する能力のカテゴリ。
  final AttributeKey key;

  /// 判定に使う詳細能力。無ければカテゴリの平均で判定する。
  final Detail? detail;

  /// 判定の基準値。能力値がこれと同じでも五分にはならず、少し不利。
  final int difficulty;

  final Outcome outcome;
  final String successText;
  final String failureText;
}

/// 試合中に提示される1つの局面。
class Scenario {
  const Scenario({
    required this.id,
    required this.situation,
    required this.options,
  });

  final String id;
  final String situation;
  final List<ScenarioOption> options;
}

/// ポジション別の局面プール。
///
/// 各局面は「難しいが得点に直結する手」と「安全だが見返りが小さい手」を
/// 対にしてある。どちらを選ぶかがこのゲームの判断そのものなので、
/// 常に正解になる選択肢を作らない。
///
/// 1試合で3つ引くので、各ポジション7つあれば同じ組み合わせは
/// 数試合に一度しか出ない。3つしか無いと毎試合同じ顔ぶれになる。
class ScenarioPool {
  const ScenarioPool._();

  static List<Scenario> forPosition(Position position) =>
      forFamily(position.family);

  static List<Scenario> forFamily(ScenarioFamily family) => switch (family) {
        ScenarioFamily.goalkeeper => goalkeeper,
        ScenarioFamily.defence => defence,
        ScenarioFamily.midfield => midfield,
        ScenarioFamily.forward => forward,
      };

  static const List<Scenario> goalkeeper = [
    Scenario(
      id: 'gk-oneonone',
      situation: '相手FWが抜け出した。1対1。距離を詰めるか、構えて待つか。',
      options: [
        ScenarioOption(
          label: '飛び出して距離を詰める',
          key: AttributeKey.goalkeeping,
          detail: Detail.gkPositioning,
          difficulty: 70,
          outcome: Outcome.play,
          successText: '一気に間合いを詰め、足元でシュートを止めた。',
          failureText: '飛び出しが早く、ループで頭上を抜かれた。',
        ),
        ScenarioOption(
          label: '構えてコースを消す',
          key: AttributeKey.goalkeeping,
          detail: Detail.gkPositioning,
          difficulty: 58,
          outcome: Outcome.play,
          successText: '体を大きく見せてコースを消し、正面で止めた。',
          failureText: '読みが外れ、逆を突かれた。',
        ),
        ScenarioOption(
          label: '足を使って時間を稼ぐ',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 50,
          outcome: Outcome.play,
          successText: '寄せる角度を変えて遅らせ、DFの帰陣を待てた。',
          failureText: '中途半端な位置取りで、簡単に決められた。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-cross',
      situation: 'ゴール前に高いクロス。相手FWと自分のDFが競っている。',
      options: [
        ScenarioOption(
          label: 'パンチングで弾く',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 62,
          outcome: Outcome.play,
          successText: '混戦を避けて遠くへ弾き出した。',
          failureText: 'パンチングが弱く、こぼれ球を押し込まれかけた。',
        ),
        ScenarioOption(
          label: 'キャッチに行く',
          key: AttributeKey.goalkeeping,
          detail: Detail.handling,
          difficulty: 72,
          outcome: Outcome.play,
          successText: '最高点で掴み、そのまま速攻を始めた。',
          failureText: '手から弾き、目の前に落としてしまった。',
        ),
        ScenarioOption(
          label: 'ラインに留まってDFに任せる',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 46,
          outcome: Outcome.play,
          successText: 'DFがクリアしやすい位置を保ち、危険を消した。',
          failureText: 'DFと譲り合い、誰も触れなかった。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-pk',
      situation: 'PKを与えてしまった。キッカーが助走に入る。',
      options: [
        ScenarioOption(
          label: '読んで先に飛ぶ',
          key: AttributeKey.goalkeeping,
          detail: Detail.reflexes,
          difficulty: 78,
          outcome: Outcome.play,
          successText: '読み勝った。両手で弾き出し、スタジアムが沸いた。',
          failureText: '逆に飛んだ。ボールは反対側へ。',
        ),
        ScenarioOption(
          label: 'ぎりぎりまで待つ',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 74,
          outcome: Outcome.play,
          successText: '最後まで待ち、反応でセーブした。',
          failureText: '待ちすぎて、隅への強いボールに届かなかった。',
        ),
        ScenarioOption(
          label: '中央で構える',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 66,
          outcome: Outcome.play,
          successText: 'キッカーが迷った。真ん中に蹴ったボールを止めた。',
          failureText: 'キッカーは迷わず隅へ蹴った。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-distribution',
      situation: 'ボールをキャッチした。相手は前掛かりで、前線に味方が1人残っている。',
      options: [
        ScenarioOption(
          label: '前線へロングスローを投げる',
          key: AttributeKey.passing,
          detail: Detail.longPassing,
          difficulty: 68,
          outcome: Outcome.assist,
          successText: '一本のスローで前線へ。味方が抜け出して決めた。',
          failureText: '距離が足りず、相手に拾われた。',
        ),
        ScenarioOption(
          label: '大きく蹴り出す',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 50,
          outcome: Outcome.play,
          successText: '陣地を大きく回復し、相手の圧力を逃した。',
          failureText: 'キックが流れ、相手のスローインになった。',
        ),
        ScenarioOption(
          label: '近くのDFに繋ぐ',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 42,
          outcome: Outcome.play,
          successText: '落ち着いて繋ぎ、ビルドアップを始めた。',
          failureText: 'DFへのパスが弱く、相手FWに狙われた。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-longshot',
      situation: '25mからのミドルシュート。ボールが揺れながら飛んでくる。',
      options: [
        ScenarioOption(
          label: 'キャッチする',
          key: AttributeKey.goalkeeping,
          detail: Detail.handling,
          difficulty: 74,
          outcome: Outcome.play,
          successText: '揺れるボールを胸に収めた。',
          failureText: '手から弾き、こぼれ球を詰められた。',
        ),
        ScenarioOption(
          label: '横に弾く',
          key: AttributeKey.goalkeeping,
          detail: Detail.reflexes,
          difficulty: 58,
          outcome: Outcome.play,
          successText: '無理をせず、コーナーへ弾き出した。',
          failureText: '弾いた先に相手がいた。',
        ),
        ScenarioOption(
          label: '体で受ける',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 52,
          outcome: Outcome.play,
          successText: '体の正面で受け止め、こぼれ球も自分で抑えた。',
          failureText: '当たったボールが股を抜けた。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-sweeper',
      situation: 'DFの背後に長いボール。相手FWと自分、どちらが先に触るか。',
      options: [
        ScenarioOption(
          label: 'エリアの外まで飛び出してクリア',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 70,
          outcome: Outcome.play,
          successText: 'エリア外で先に触り、大きくクリアした。',
          failureText: '間に合わず、無人のゴールへ蹴り込まれた。',
        ),
        ScenarioOption(
          label: 'エリア内で待って処理する',
          key: AttributeKey.goalkeeping,
          detail: Detail.gkPositioning,
          difficulty: 56,
          outcome: Outcome.play,
          successText: '慌てず待ち、エリア内で確実に処理した。',
          failureText: '待ちすぎて、FWにボールを収められた。',
        ),
        ScenarioOption(
          label: 'DFに声をかけて任せる',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 48,
          outcome: Outcome.play,
          successText: '声で味方を動かし、DFが先に触った。',
          failureText: '指示が伝わらず、DFとぶつかった。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-lastminute',
      situation: '後半アディショナルタイム、1点リード。相手GKまで上がってきたコーナー。',
      options: [
        ScenarioOption(
          label: '飛び出してキャッチ',
          key: AttributeKey.goalkeeping,
          detail: Detail.handling,
          difficulty: 72,
          outcome: Outcome.play,
          successText: '混戦の中で掴み切った。試合を締めた。',
          failureText: '触れず、こぼれ球を押し込まれた。',
        ),
        ScenarioOption(
          label: 'ライン上で待つ',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 60,
          outcome: Outcome.play,
          successText: 'ライン上で反応し、至近距離を止めた。',
          failureText: '密集で視界を塞がれ、反応できなかった。',
        ),
        ScenarioOption(
          label: 'クリア後に前へ投げて速攻',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 64,
          outcome: Outcome.assist,
          successText: 'クリアを拾って前へ投げ、無人のゴールに味方が決めた。',
          failureText: '投げたボールが弱く、相手に渡った。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-corner',
      situation: '相手のコーナーキック。ゴール前は人で埋まっている。',
      options: [
        ScenarioOption(
          label: 'パンチングで弾き出す',
          key: AttributeKey.goalkeeping,
          detail: Detail.handling,
          difficulty: 62,
          outcome: Outcome.play,
          successText: '拳で遠くへ弾いた。危険な場所から消えた。',
          failureText: '中途半端な弾きが、相手の前にこぼれた。',
        ),
        ScenarioOption(
          label: '飛び出して掴む',
          key: AttributeKey.goalkeeping,
          detail: Detail.gkPositioning,
          difficulty: 72,
          outcome: Outcome.play,
          successText: '人垣の中から両手で掴み取った。ゴール前が静かになる。',
          failureText: '人に当たって届かず、ゴール前に落ちた。',
        ),
        ScenarioOption(
          label: 'ライン上に残って備える',
          key: AttributeKey.goalkeeping,
          detail: Detail.reflexes,
          difficulty: 52,
          outcome: Outcome.play,
          successText: '至近距離のヘディングに反応し、足で止めた。',
          failureText: '見送ったボールが、そのままネットに吸い込まれた。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-backpass',
      situation: '味方から苦しいバックパス。相手FWが全力で寄せてくる。',
      options: [
        ScenarioOption(
          label: '大きく蹴り出す',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 46,
          outcome: Outcome.play,
          successText: 'タッチラインの外まで蹴り出した。まずは安全に。',
          failureText: 'ミートせず、相手の足元へ転がった。',
        ),
        ScenarioOption(
          label: '持ち出してかわす',
          key: AttributeKey.dribbling,
          detail: Detail.ballControl,
          difficulty: 75,
          outcome: Outcome.play,
          successText: '一歩ずらして寄せをかわし、時間を作った。',
          failureText: '足元をつつかれ、無人のゴールを晒した。',
        ),
        ScenarioOption(
          label: '空いた味方へ短くつける',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 63,
          outcome: Outcome.play,
          successText: '寄せの外へ的確につけ、相手のプレスを外した。',
          failureText: 'パスが弱く、危険な位置で奪われた。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-rebound',
      situation: '一度は弾いた。こぼれ球に相手が詰めてくる。',
      options: [
        ScenarioOption(
          label: '前に出て抑え込む',
          key: AttributeKey.goalkeeping,
          detail: Detail.reflexes,
          difficulty: 70,
          outcome: Outcome.play,
          successText: '体ごと覆いかぶさり、ボールを収めた。',
          failureText: '一歩遅れ、蹴り込まれた。',
        ),
        ScenarioOption(
          label: '足でコーナーに逃げる',
          key: AttributeKey.goalkeeping,
          detail: Detail.handling,
          difficulty: 58,
          outcome: Outcome.play,
          successText: '伸ばした足に当て、ラインの外へ逃した。',
          failureText: '当たりが甘く、ゴール前に残ってしまった。',
        ),
        ScenarioOption(
          label: '構え直して次に備える',
          key: AttributeKey.goalkeeping,
          detail: Detail.gkPositioning,
          difficulty: 50,
          outcome: Outcome.play,
          successText: '角度を切って構え、至近距離の一撃を弾き返した。',
          failureText: '重心が残り、逆を突かれた。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-rain',
      situation: '雨脚が強い。ゴール前に浮き球が落ちてくる。手が滑る。',
      options: [
        ScenarioOption(
          label: 'キャッチにいく',
          key: AttributeKey.goalkeeping,
          detail: Detail.handling,
          difficulty: 74,
          outcome: Outcome.play,
          successText: '濡れたボールを、指先までしっかり掴んだ。',
          failureText: '手からこぼれ、ゴール前に転がった。',
        ),
        ScenarioOption(
          label: '両手で確実に弾く',
          key: AttributeKey.goalkeeping,
          detail: Detail.reflexes,
          difficulty: 56,
          outcome: Outcome.play,
          successText: '無理をせず前に弾き、味方がクリアした。',
          failureText: '弾いた先に相手がいた。',
        ),
        ScenarioOption(
          label: '味方に任せて声を出す',
          key: AttributeKey.passing,
          detail: Detail.vision,
          difficulty: 52,
          outcome: Outcome.play,
          successText: '一声でDFが動き、危なげなく処理した。',
          failureText: '声が届かず、味方と交錯した。',
        ),
      ],
    ),
    Scenario(
      id: 'gk-line',
      situation: '押し込まれている。最終ラインがずるずる下がってきた。',
      options: [
        ScenarioOption(
          label: '声でラインを押し上げる',
          key: AttributeKey.passing,
          detail: Detail.vision,
          difficulty: 60,
          outcome: Outcome.play,
          successText: 'ラインが揃い、相手の攻撃が窮屈になった。',
          failureText: '中途半端に上げ、背後を取られた。',
        ),
        ScenarioOption(
          label: '自分が高い位置を取る',
          key: AttributeKey.goalkeeping,
          detail: Detail.gkPositioning,
          difficulty: 68,
          outcome: Outcome.play,
          successText: '背後のボールを先回りして処理した。',
          failureText: '出た背中を狙われ、ループを浴びた。',
        ),
        ScenarioOption(
          label: '深く構えて跳ね返しに備える',
          key: AttributeKey.goalkeeping,
          detail: Detail.reflexes,
          difficulty: 50,
          outcome: Outcome.play,
          successText: '立て続けのシュートを、体で止め続けた。',
          failureText: '押し込まれ続け、ついにこじ開けられた。',
        ),
      ],
    ),
  ];

  static const List<Scenario> forward = [
    Scenario(
      id: 'fw-box',
      situation: 'ペナルティエリア内でボールを受けた。DFが2枚寄せてくる。',
      options: [
        ScenarioOption(
          label: '強引にシュートを打つ',
          key: AttributeKey.shooting,
          detail: Detail.shotPower,
          difficulty: 72,
          outcome: Outcome.goal,
          successText: '寄せられる前に振り抜いた。ネットが揺れる。',
          failureText: '体勢が崩れ、枠を大きく外した。',
        ),
        ScenarioOption(
          label: '横の味方に落とす',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 55,
          outcome: Outcome.assist,
          successText: '柔らかく落としたボールを味方が流し込んだ。',
          failureText: 'パスがずれ、DFにカットされた。',
        ),
        ScenarioOption(
          label: 'キープして味方を待つ',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 48,
          outcome: Outcome.play,
          successText: '体を入れて時間を作り、攻撃を落ち着かせた。',
          failureText: '力負けしてボールを失った。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-through',
      situation: '最終ラインの裏へスルーパスが出た。GKが飛び出してくる。',
      options: [
        ScenarioOption(
          label: 'ループシュートを狙う',
          key: AttributeKey.shooting,
          detail: Detail.finishing,
          difficulty: 68,
          outcome: Outcome.goal,
          successText: 'GKの頭上を越えるループ。美しく決まった。',
          failureText: '高すぎた。ボールはバーの上へ消えた。',
        ),
        ScenarioOption(
          label: 'GKをかわして流し込む',
          key: AttributeKey.dribbling,
          detail: Detail.dribbling,
          difficulty: 74,
          outcome: Outcome.goal,
          successText: '軽くかわして無人のゴールへ流し込んだ。',
          failureText: '足に当てられ、ボールがこぼれた。',
        ),
        ScenarioOption(
          label: '走り込む味方へ横パス',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 58,
          outcome: Outcome.assist,
          successText: '冷静な横パス。味方が無人のゴールへ押し込んだ。',
          failureText: 'パスが強すぎて味方が追いつけなかった。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-cross',
      situation: 'サイドからクロスが上がる。DFとの空中戦になる。',
      options: [
        ScenarioOption(
          label: 'ヘディングで叩きつける',
          key: AttributeKey.physical,
          detail: Detail.jumping,
          difficulty: 70,
          outcome: Outcome.goal,
          successText: '競り合いに勝ち、ヘディングをゴール左隅へ。',
          failureText: '競り負けて、DFにクリアされた。',
        ),
        ScenarioOption(
          label: 'ニアで潰れて味方を空ける',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 45,
          outcome: Outcome.assist,
          successText: 'ニアでDFを引き付け、空いた味方が押し込んだ。',
          failureText: '中途半端な動きで、味方ごと消えてしまった。',
        ),
        ScenarioOption(
          label: '下がってこぼれ球を狙う',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 60,
          outcome: Outcome.goal,
          successText: 'こぼれ球に誰よりも早く反応し、押し込んだ。',
          failureText: '読みが外れ、こぼれ球は相手の足元へ。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-counter',
      situation: '自陣でボールを奪った。相手DFは2人だけ、こちらは自分と味方の2人。',
      options: [
        ScenarioOption(
          label: '全力で駆け上がって受ける',
          key: AttributeKey.pace,
          detail: Detail.sprintSpeed,
          difficulty: 66,
          outcome: Outcome.goal,
          successText: 'DFを置き去りにして受け、そのまま決めた。',
          failureText: '追いつかれ、シュートはブロックされた。',
        ),
        ScenarioOption(
          label: 'DFを引き付けて味方に流す',
          key: AttributeKey.dribbling,
          detail: Detail.dribbling,
          difficulty: 60,
          outcome: Outcome.assist,
          successText: 'DFを2人とも引き付けてから流し、味方がフリーで決めた。',
          failureText: '引き付けすぎて、自分ごと潰された。',
        ),
        ScenarioOption(
          label: '無理せずポゼッションに切り替える',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 40,
          outcome: Outcome.play,
          successText: '速攻を捨てて確実に繋ぎ、押し込む形を作った。',
          failureText: '判断が遅れ、相手の帰陣を許した。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-pk',
      situation: 'PKを獲得した。キッカーは自分。GKがラインで揺さぶってくる。',
      options: [
        ScenarioOption(
          label: '隅を狙って強く蹴る',
          key: AttributeKey.shooting,
          detail: Detail.shotPower,
          difficulty: 62,
          outcome: Outcome.goal,
          successText: 'GKの逆を突いた。隅に突き刺さる。',
          failureText: '狙いすぎてポストに当たり、外へ。',
        ),
        ScenarioOption(
          label: 'GKの動きを見て逆に蹴る',
          key: AttributeKey.dribbling,
          detail: Detail.agility,
          difficulty: 58,
          outcome: Outcome.goal,
          successText: 'GKが先に動いた。ゆっくりと逆へ転がした。',
          failureText: 'GKが動かず、弱いキックを止められた。',
        ),
        ScenarioOption(
          label: '味方に譲る',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 30,
          outcome: Outcome.play,
          successText: '調子の良い味方に譲った。チームは冷静に決めた。',
          failureText: '譲った味方が外し、責任だけが残った。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-press',
      situation: '相手GKがビルドアップを始める。前線からプレスに行くか。',
      options: [
        ScenarioOption(
          label: 'GKに全力で寄せる',
          key: AttributeKey.pace,
          detail: Detail.sprintSpeed,
          difficulty: 64,
          outcome: Outcome.goal,
          successText: 'GKのパスミスを誘い、無人のゴールへ蹴り込んだ。',
          failureText: '簡単にかわされ、背後を大きく空けた。',
        ),
        ScenarioOption(
          label: 'パスコースを切って追い込む',
          key: AttributeKey.defending,
          detail: Detail.interceptions,
          difficulty: 52,
          outcome: Outcome.play,
          successText: 'コースを限定し、相手は苦し紛れに蹴り出した。',
          failureText: '寄せが甘く、楽に前線へ繋がれた。',
        ),
        ScenarioOption(
          label: '守備ブロックに戻る',
          key: AttributeKey.physical,
          detail: Detail.stamina,
          difficulty: 40,
          outcome: Outcome.play,
          successText: '無駄走りをせず、守備の形を整えた。',
          failureText: '戻りが遅れ、中盤との距離が空いた。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-lastminute',
      situation: '後半アディショナルタイム。コーナーキックがこぼれてきた。',
      options: [
        ScenarioOption(
          label: 'ボレーで叩く',
          key: AttributeKey.shooting,
          detail: Detail.longShots,
          difficulty: 76,
          outcome: Outcome.goal,
          successText: '完璧なボレー。スタジアムが揺れた。',
          failureText: '当たり損ないが宇宙へ飛んでいった。',
        ),
        ScenarioOption(
          label: 'トラップしてから狙う',
          key: AttributeKey.dribbling,
          detail: Detail.ballControl,
          difficulty: 64,
          outcome: Outcome.goal,
          successText: '一度収めて冷静に流し込んだ。',
          failureText: 'トラップが大きく、寄せられて潰された。',
        ),
        ScenarioOption(
          label: 'ファーの味方へ折り返す',
          key: AttributeKey.passing,
          detail: Detail.crossing,
          difficulty: 56,
          outcome: Outcome.assist,
          successText: 'ファーへの折り返しを味方が押し込んだ。',
          failureText: '折り返しが弱く、クリアされた。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-header',
      situation: 'ファーサイドへのクロス。DFと並んで走り込んだ。',
      options: [
        ScenarioOption(
          label: 'ヘディングで叩きつける',
          key: AttributeKey.shooting,
          detail: Detail.heading,
          difficulty: 70,
          outcome: Outcome.goal,
          successText: '高い打点から地面に叩きつけた。GKは動けない。',
          failureText: '当たりが薄く、枠の上へ消えた。',
        ),
        ScenarioOption(
          label: '折り返して中央へ',
          key: AttributeKey.passing,
          detail: Detail.crossing,
          difficulty: 60,
          outcome: Outcome.assist,
          successText: '頭で中央へ折り返し、味方が押し込んだ。',
          failureText: '折り返しが弱く、GKに収まった。',
        ),
        ScenarioOption(
          label: 'DFを引き付けてスペースを空ける',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 48,
          outcome: Outcome.play,
          successText: '2人を引き連れ、空いた場所から味方が飛び込んだ。',
          failureText: '中途半端な動きで、逆に味方の邪魔になった。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-offside',
      situation: '最終ラインぎりぎりでの駆け引き。出し手が顔を上げた。',
      options: [
        ScenarioOption(
          label: '一気に裏へ抜ける',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 66,
          outcome: Outcome.play,
          successText: '半歩の駆け引きに勝ち、フリーで前を向いた。',
          failureText: '出るのが早く、旗が上がった。',
        ),
        ScenarioOption(
          label: '足元で受けにいく',
          key: AttributeKey.dribbling,
          detail: Detail.ballControl,
          difficulty: 55,
          outcome: Outcome.play,
          successText: '下りて受け、味方の押し上げを待った。',
          failureText: '背後から潰され、ボールを失った。',
        ),
        ScenarioOption(
          label: 'ワンテンポ遅らせて出る',
          key: AttributeKey.passing,
          detail: Detail.vision,
          difficulty: 63,
          outcome: Outcome.play,
          successText: '出し手と目が合った。完璧なタイミングで抜け出した。',
          failureText: '待ちすぎて、コースを消された。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-hold',
      situation: '背負って受けた。DFが背中から強く当たってくる。',
      options: [
        ScenarioOption(
          label: '体を張ってキープ',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 62,
          outcome: Outcome.play,
          successText: '当たりに耐え、味方が上がる時間を作った。',
          failureText: '力負けし、後ろから刈り取られた。',
        ),
        ScenarioOption(
          label: '反転して仕掛ける',
          key: AttributeKey.dribbling,
          detail: Detail.agility,
          difficulty: 74,
          outcome: Outcome.play,
          successText: '重心を外して反転。一気にゴールへ向かった。',
          failureText: '反転しきれず、囲まれて失った。',
        ),
        ScenarioOption(
          label: 'ワンタッチで味方に落とす',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 54,
          outcome: Outcome.assist,
          successText: '触っただけの落としが、走り込む味方に完璧に合った。',
          failureText: '落とし所が甘く、相手に渡った。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-rebound',
      situation: 'GKが弾いた。こぼれ球が目の前に転がってくる。',
      options: [
        ScenarioOption(
          label: '飛び込んで押し込む',
          key: AttributeKey.shooting,
          detail: Detail.finishing,
          difficulty: 58,
          outcome: Outcome.goal,
          successText: '誰よりも早く反応し、ゴールに押し込んだ。',
          failureText: '半歩遅れ、DFに掻き出された。',
        ),
        ScenarioOption(
          label: '落ち着いて浮かせる',
          key: AttributeKey.shooting,
          detail: Detail.finishing,
          difficulty: 68,
          outcome: Outcome.goal,
          successText: '倒れ込むGKの上を、柔らかく越えた。',
          failureText: '浮かせすぎ、クロスバーを叩いた。',
        ),
        ScenarioOption(
          label: '横の味方に合わせる',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 52,
          outcome: Outcome.assist,
          successText: '無人のゴール前へ。味方は流し込むだけだった。',
          failureText: '横パスが強すぎ、味方が合わせられなかった。',
        ),
      ],
    ),
    Scenario(
      id: 'fw-solo',
      situation: '中盤で前を向いた。相手は3人、味方が追い越そうとしている。',
      options: [
        ScenarioOption(
          label: '仕掛けて一人で行く',
          key: AttributeKey.dribbling,
          detail: Detail.dribbling,
          difficulty: 76,
          outcome: Outcome.goal,
          successText: '3人を置き去りにして、そのまま流し込んだ。',
          failureText: '2人目に引っかかり、カウンターを浴びた。',
        ),
        ScenarioOption(
          label: '追い越す味方へ流す',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 58,
          outcome: Outcome.assist,
          successText: '完璧なタイミングで流し、味方が沈めた。',
          failureText: 'タイミングが合わず、オフサイドになった。',
        ),
        ScenarioOption(
          label: 'スピードで一気に運ぶ',
          key: AttributeKey.pace,
          detail: Detail.sprintSpeed,
          difficulty: 64,
          outcome: Outcome.play,
          successText: '一気に敵陣深くまで運び、味方を押し上げた。',
          failureText: '運びすぎて囲まれ、奪われた。',
        ),
      ],
    ),
  ];

  static const List<Scenario> midfield = [
    Scenario(
      id: 'mf-build',
      situation: '中盤でボールを持った。前線は密集、サイドは空いている。',
      options: [
        ScenarioOption(
          label: '縦にスルーパスを通す',
          key: AttributeKey.passing,
          detail: Detail.vision,
          difficulty: 70,
          outcome: Outcome.assist,
          successText: '密集の間を通す一本。FWが抜け出して決めた。',
          failureText: 'コースが甘く、インターセプトされた。',
        ),
        ScenarioOption(
          label: 'サイドへ大きく展開する',
          key: AttributeKey.passing,
          detail: Detail.longPassing,
          difficulty: 52,
          outcome: Outcome.play,
          successText: '逆サイドへ正確な展開。試合が動き出す。',
          failureText: '距離が足りず、タッチラインを割った。',
        ),
        ScenarioOption(
          label: '自分で持ち上がる',
          key: AttributeKey.dribbling,
          detail: Detail.dribbling,
          difficulty: 66,
          outcome: Outcome.play,
          successText: '2人剥がして前進。相手の守備が崩れた。',
          failureText: '囲まれて奪われ、カウンターを受けた。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-shot',
      situation: 'ペナルティエリア手前にこぼれ球。前は空いている。',
      options: [
        ScenarioOption(
          label: 'ミドルシュートを打つ',
          key: AttributeKey.shooting,
          detail: Detail.longShots,
          difficulty: 74,
          outcome: Outcome.goal,
          successText: '鋭いミドルがゴール右上に突き刺さった。',
          failureText: 'ミートが甘く、GKの正面に飛んだ。',
        ),
        ScenarioOption(
          label: '中央へ持ち出してから叩く',
          key: AttributeKey.dribbling,
          detail: Detail.ballControl,
          difficulty: 62,
          outcome: Outcome.assist,
          successText: '角度を作ってから横へ。味方が押し込んだ。',
          failureText: '持ち出しが大きく、DFに引っかかった。',
        ),
        ScenarioOption(
          label: '無理せず作り直す',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 42,
          outcome: Outcome.play,
          successText: '後ろに戻して作り直し。危なげない判断。',
          failureText: 'バックパスが短く、相手に拾われかけた。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-press',
      situation: '相手のビルドアップ。プレスに行くか、ブロックを作るか。',
      options: [
        ScenarioOption(
          label: '一気に寄せて奪いに行く',
          key: AttributeKey.defending,
          detail: Detail.tackling,
          difficulty: 68,
          outcome: Outcome.play,
          successText: '寄せ切ってボールを奪取。ショートカウンターへ。',
          failureText: 'かわされ、間延びした中盤を使われた。',
        ),
        ScenarioOption(
          label: 'パスコースを切って待つ',
          key: AttributeKey.defending,
          detail: Detail.interceptions,
          difficulty: 50,
          outcome: Outcome.play,
          successText: 'コースを消し続け、相手は後ろに戻すしかなかった。',
          failureText: '中途半端な立ち位置で、間を通された。',
        ),
        ScenarioOption(
          label: '走力で背後をカバーする',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 58,
          outcome: Outcome.play,
          successText: '背後のスペースを消し切り、決定機を未然に潰した。',
          failureText: '戻り切れず、危険なスペースを空けた。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-freekick',
      situation: 'ゴール正面25mでFKを得た。壁は5枚。',
      options: [
        ScenarioOption(
          label: '壁を越えて直接狙う',
          key: AttributeKey.shooting,
          detail: Detail.longShots,
          difficulty: 78,
          outcome: Outcome.goal,
          successText: '壁を越えて落ちる軌道。GKは一歩も動けなかった。',
          failureText: '壁に当たった。こぼれ球は相手へ。',
        ),
        ScenarioOption(
          label: 'ファーへ巻いたボールを入れる',
          key: AttributeKey.passing,
          detail: Detail.crossing,
          difficulty: 60,
          outcome: Outcome.assist,
          successText: 'ファーへの巻いたボールを、味方が頭で合わせた。',
          failureText: 'GKに直接キャッチされた。',
        ),
        ScenarioOption(
          label: '横に出してリスタート',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 36,
          outcome: Outcome.play,
          successText: '意表を突く横パスから、攻撃を組み立て直した。',
          failureText: 'ただの相手ボールになった。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-transition',
      situation: '相手のカウンター。自分の前にボール保持者、後ろは手薄。',
      options: [
        ScenarioOption(
          label: '体を張って止める',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 66,
          outcome: Outcome.play,
          successText: '正面から止め切った。相手の勢いを断った。',
          failureText: '吹き飛ばされ、決定機を許した。',
        ),
        ScenarioOption(
          label: 'ファウルで止める',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 44,
          outcome: Outcome.play,
          successText: 'カードは覚悟の上。戦術的ファウルで流れを切った。',
          failureText: 'ファウルが遅れ、アドバンテージで流された。',
        ),
        ScenarioOption(
          label: '遅らせて味方の帰陣を待つ',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 56,
          outcome: Outcome.play,
          successText: '巧みに遅らせ、味方が戻る時間を作った。',
          failureText: '簡単に抜かれ、数的不利のまま攻め込まれた。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-switch',
      situation: '相手が片側に寄っている。逆サイドに味方がフリーで待っている。',
      options: [
        ScenarioOption(
          label: '40mのサイドチェンジを通す',
          key: AttributeKey.passing,
          detail: Detail.vision,
          difficulty: 64,
          outcome: Outcome.assist,
          successText: '一本で逆サイドへ。フリーの味方が持ち込んで決めた。',
          failureText: '風に流され、タッチラインを割った。',
        ),
        ScenarioOption(
          label: '近くの味方と繋いで運ぶ',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 46,
          outcome: Outcome.play,
          successText: 'テンポ良く繋ぎ、相手を走らせた。',
          failureText: '狭い場所で引っかかり、奪われた。',
        ),
        ScenarioOption(
          label: '密集を1人で突破する',
          key: AttributeKey.dribbling,
          detail: Detail.dribbling,
          difficulty: 72,
          outcome: Outcome.goal,
          successText: '3人をかわして持ち込み、自ら決めた。',
          failureText: '2人目に止められ、カウンターを食らった。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-late',
      situation: '後半40分、1点ビハインド。ボールは自分の足元、前に空きはない。',
      options: [
        ScenarioOption(
          label: 'ペナルティエリアに飛び込む',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 66,
          outcome: Outcome.goal,
          successText: '走り込んだところに折り返しが来た。同点弾。',
          failureText: '走り込んだが、ボールは来なかった。',
        ),
        ScenarioOption(
          label: '早いクロスを上げる',
          key: AttributeKey.passing,
          detail: Detail.crossing,
          difficulty: 58,
          outcome: Outcome.assist,
          successText: '早いクロスにFWが合わせた。',
          failureText: 'クロスは誰にも合わず、流れた。',
        ),
        ScenarioOption(
          label: 'テンポを落として組み立てる',
          key: AttributeKey.dribbling,
          detail: Detail.agility,
          difficulty: 44,
          outcome: Outcome.play,
          successText: '焦らず組み立て、良い形を作った。',
          failureText: '時間だけが過ぎていった。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-halfspace',
      situation: 'ライン間で前を向いて受けた。中央は密集、外は空いている。',
      options: [
        ScenarioOption(
          label: 'スルーパスを通す',
          key: AttributeKey.passing,
          detail: Detail.vision,
          difficulty: 73,
          outcome: Outcome.assist,
          successText: '密集の隙間を通した。抜け出した味方が決めた。',
          failureText: '狙いは見えていたが、体に当たった。',
        ),
        ScenarioOption(
          label: 'そのまま持ち上がる',
          key: AttributeKey.dribbling,
          detail: Detail.dribbling,
          difficulty: 68,
          outcome: Outcome.play,
          successText: '運びながら相手を引き付け、味方を解放した。',
          failureText: '囲まれてボールを失った。',
        ),
        ScenarioOption(
          label: '後ろに戻して作り直す',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 46,
          outcome: Outcome.play,
          successText: '無理をせず、攻撃をやり直した。',
          failureText: '戻したパスが短く、狙われた。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-recover',
      situation: 'ボールを失った直後。5秒以内に取り返したい。',
      options: [
        ScenarioOption(
          label: '即座に潰しに行く',
          key: AttributeKey.defending,
          detail: Detail.tackling,
          difficulty: 70,
          outcome: Outcome.play,
          successText: '振り向く前に潰し、そのまま攻撃に転じた。',
          failureText: 'かわされ、前を向かれた。',
        ),
        ScenarioOption(
          label: 'パスコースに立つ',
          key: AttributeKey.defending,
          detail: Detail.interceptions,
          difficulty: 61,
          outcome: Outcome.play,
          successText: '出しどころを消し、苦し紛れの縦パスを奪った。',
          failureText: '読みが外れ、逆を取られた。',
        ),
        ScenarioOption(
          label: '自陣に戻って形を作る',
          key: AttributeKey.physical,
          detail: Detail.stamina,
          difficulty: 48,
          outcome: Outcome.play,
          successText: '全力で戻り、守備の枚数を揃えた。',
          failureText: '足が止まり、間に合わなかった。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-longshot',
      situation: '相手のブロックが下がった。ミドルのコースが空いている。',
      options: [
        ScenarioOption(
          label: 'ミドルシュートを打つ',
          key: AttributeKey.shooting,
          detail: Detail.longShots,
          difficulty: 72,
          outcome: Outcome.goal,
          successText: '無回転気味の一撃。ゴール左上に突き刺さった。',
          failureText: '当たり損ね。ボールは大きく枠を外れた。',
        ),
        ScenarioOption(
          label: '前線に楔を入れる',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 60,
          outcome: Outcome.assist,
          successText: '足元に鋭く入り、そこから流れるように決まった。',
          failureText: '強すぎた。相手に当たって跳ね返った。',
        ),
        ScenarioOption(
          label: 'サイドに振って作り直す',
          key: AttributeKey.passing,
          detail: Detail.longPassing,
          difficulty: 50,
          outcome: Outcome.play,
          successText: '逆サイドへ丁寧に。相手の陣形が伸びた。',
          failureText: '距離が合わず、タッチを割った。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-tempo',
      situation: '押し込まれている時間帯。味方の足が止まってきた。',
      options: [
        ScenarioOption(
          label: 'ボールを持って時間を作る',
          key: AttributeKey.dribbling,
          detail: Detail.ballControl,
          difficulty: 63,
          outcome: Outcome.play,
          successText: '一人で相手を2人剥がし、チームが息を吹き返した。',
          failureText: '囲まれ、危険な位置で奪われた。',
        ),
        ScenarioOption(
          label: '縦に速く展開して逃げる',
          key: AttributeKey.passing,
          detail: Detail.longPassing,
          difficulty: 66,
          outcome: Outcome.play,
          successText: '一本で押し返し、相手を自陣へ戻した。',
          failureText: '精度を欠き、すぐに返された。',
        ),
        ScenarioOption(
          label: '相手のキーマンを消す',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 58,
          outcome: Outcome.play,
          successText: '起点を消し続け、波が止まった。',
          failureText: '振り切られ、決定機を作られた。',
        ),
      ],
    ),
    Scenario(
      id: 'mf-corner',
      situation: '自分がコーナーキックを蹴る。中の枚数は五分。',
      options: [
        ScenarioOption(
          label: 'ニアに速いボール',
          key: AttributeKey.passing,
          detail: Detail.crossing,
          difficulty: 69,
          outcome: Outcome.assist,
          successText: '速い球にニアで合わせた。そらしたボールがネットへ。',
          failureText: '速すぎて誰も触れず、そのまま流れた。',
        ),
        ScenarioOption(
          label: 'ファーへふわりと上げる',
          key: AttributeKey.passing,
          detail: Detail.crossing,
          difficulty: 62,
          outcome: Outcome.assist,
          successText: '大外で待つ味方の頭にぴたりと合った。',
          failureText: '滞空時間が長く、GKに掴まれた。',
        ),
        ScenarioOption(
          label: 'ショートコーナーで崩す',
          key: AttributeKey.dribbling,
          detail: Detail.ballControl,
          difficulty: 55,
          outcome: Outcome.play,
          successText: '短くつないで角度を変え、崩しの形を作った。',
          failureText: '狭い場所で奪われ、カウンターを受けた。',
        ),
      ],
    ),
  ];

  static const List<Scenario> defence = [
    Scenario(
      id: 'df-duel',
      situation: '快足のウイングと1対1。背後にはスペースがある。',
      options: [
        ScenarioOption(
          label: '飛び込んで奪いに行く',
          key: AttributeKey.defending,
          detail: Detail.tackling,
          difficulty: 72,
          outcome: Outcome.play,
          successText: '足を伸ばして完璧なタックル。ボールだけを奪った。',
          failureText: '簡単にかわされ、決定機を作られた。',
        ),
        ScenarioOption(
          label: '間合いを保って遅らせる',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 55,
          outcome: Outcome.play,
          successText: '距離を保って遅らせ、味方の帰陣を待った。',
          failureText: '下がりすぎてシュートを許した。',
        ),
        ScenarioOption(
          label: '体を当てて外へ追い出す',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 62,
          outcome: Outcome.play,
          successText: '体を当ててタッチラインの外へ追い出した。',
          failureText: '倒してしまい、危険な位置でFKを与えた。',
        ),
      ],
    ),
    Scenario(
      id: 'df-cross',
      situation: '相手のクロスがゴール前へ。中には長身のFWがいる。',
      options: [
        ScenarioOption(
          label: '競り勝ってクリアする',
          key: AttributeKey.physical,
          detail: Detail.jumping,
          difficulty: 68,
          outcome: Outcome.play,
          successText: '高い打点で跳ね返し、危険を完全に排除した。',
          failureText: '競り負け、決定的なヘディングを許した。',
        ),
        ScenarioOption(
          label: 'コースに入ってブロック',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 60,
          outcome: Outcome.play,
          successText: '体を投げ出してシュートをブロックした。',
          failureText: '一歩遅く、コースを空けてしまった。',
        ),
        ScenarioOption(
          label: '前に出てインターセプト',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 70,
          outcome: Outcome.play,
          successText: '読み切って前で断ち切り、そのまま攻撃に転じた。',
          failureText: '飛び出しが空振りし、背後を使われた。',
        ),
      ],
    ),
    Scenario(
      id: 'df-buildup',
      situation: '最終ラインでボールを持つ。相手FWがプレスに来る。',
      options: [
        ScenarioOption(
          label: '縦に長いフィードを蹴る',
          key: AttributeKey.passing,
          detail: Detail.longPassing,
          difficulty: 66,
          outcome: Outcome.assist,
          successText: '一本のフィードで前線へ。そのまま得点に繋がった。',
          failureText: '精度を欠き、簡単に相手ボールになった。',
        ),
        ScenarioOption(
          label: '運んでからパスを出す',
          key: AttributeKey.dribbling,
          detail: Detail.dribbling,
          difficulty: 58,
          outcome: Outcome.play,
          successText: '数歩持ち上がって相手を外し、確実に繋いだ。',
          failureText: '奪われて、自陣で決定機を与えた。',
        ),
        ScenarioOption(
          label: '安全に大きく蹴り出す',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 38,
          outcome: Outcome.play,
          successText: '無理をせずクリア。まずは危険を消した。',
          failureText: 'ミスキックになり、スローインを与えた。',
        ),
      ],
    ),
    Scenario(
      id: 'df-setpiece',
      situation: '味方のコーナーキック。自分もゴール前に上がっている。',
      options: [
        ScenarioOption(
          label: 'ニアに飛び込んでヘディング',
          key: AttributeKey.physical,
          detail: Detail.jumping,
          difficulty: 70,
          outcome: Outcome.goal,
          successText: 'ニアで競り勝ち、頭で叩き込んだ。DFの得点。',
          failureText: 'マークを外せず、触れなかった。',
        ),
        ScenarioOption(
          label: 'ファーでこぼれ球を待つ',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 56,
          outcome: Outcome.assist,
          successText: 'こぼれ球を折り返し、味方が押し込んだ。',
          failureText: 'ボールは来ず、カウンターの戻りが遅れた。',
        ),
        ScenarioOption(
          label: '上がらずリスク管理する',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 40,
          outcome: Outcome.play,
          successText: '残っていたおかげでカウンターを未然に防いだ。',
          failureText: '一人残ったが、それでも背後を突かれた。',
        ),
      ],
    ),
    Scenario(
      id: 'df-offside',
      situation: '相手FWが裏を狙って動き出した。ラインの判断を任されている。',
      options: [
        ScenarioOption(
          label: 'ラインを上げてオフサイドを取る',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 68,
          outcome: Outcome.play,
          successText: '完璧なラインコントロール。旗が上がった。',
          failureText: 'ラインが揃わず、1人が残して裏を取られた。',
        ),
        ScenarioOption(
          label: '走り合いで潰す',
          key: AttributeKey.pace,
          detail: Detail.sprintSpeed,
          difficulty: 64,
          outcome: Outcome.play,
          successText: '走り負けせず、シュートコースを消した。',
          failureText: 'スピードで置き去りにされた。',
        ),
        ScenarioOption(
          label: 'ラインを下げて守る',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 42,
          outcome: Outcome.play,
          successText: '無理をせず下がって、ゴール前を固めた。',
          failureText: '下がりすぎて、ミドルシュートを打たれた。',
        ),
      ],
    ),
    Scenario(
      id: 'df-goalline',
      situation: 'GKがかわされた。無人のゴールに向かってシュートが飛んでくる。',
      options: [
        ScenarioOption(
          label: 'ゴールライン上でクリア',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 74,
          outcome: Outcome.play,
          successText: 'ライン上で掻き出した。歓声が上がる。',
          failureText: '間に合わず、ボールはネットへ。',
        ),
        ScenarioOption(
          label: 'スライディングでコースを消す',
          key: AttributeKey.pace,
          detail: Detail.acceleration,
          difficulty: 66,
          outcome: Outcome.play,
          successText: '滑り込んでブロック。大きなファインプレー。',
          failureText: '滑ったが届かなかった。',
        ),
        ScenarioOption(
          label: 'GKの位置に入って構える',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 48,
          outcome: Outcome.play,
          successText: '体を大きく見せて、シュートを自分に当てさせた。',
          failureText: '構えたが、股を抜かれた。',
        ),
      ],
    ),
    Scenario(
      id: 'df-overlap',
      situation: '攻撃の流れで自分がサイドを駆け上がった。前にはスペース。',
      options: [
        ScenarioOption(
          label: '深くえぐってクロス',
          key: AttributeKey.pace,
          detail: Detail.sprintSpeed,
          difficulty: 62,
          outcome: Outcome.assist,
          successText: 'ライン際までえぐったクロスを、FWが押し込んだ。',
          failureText: '追いつかれ、クロスは当たってしまった。',
        ),
        ScenarioOption(
          label: '中に切れ込んでシュート',
          key: AttributeKey.shooting,
          detail: Detail.finishing,
          difficulty: 76,
          outcome: Outcome.goal,
          successText: '切れ込んで放ったシュートが決まった。DFらしからぬ一撃。',
          failureText: 'シュートは大きく外れ、戻る距離だけが残った。',
        ),
        ScenarioOption(
          label: '早めに味方へ預ける',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 44,
          outcome: Outcome.play,
          successText: '無理をせず預け、自分は守備位置へ戻った。',
          failureText: '預けたパスが弱く、相手に拾われた。',
        ),
      ],
    ),
    Scenario(
      id: 'df-transition',
      situation: '数的不利のカウンター。自分ひとりで2人を見ている。',
      options: [
        ScenarioOption(
          label: 'ボール保持者に寄せて奪う',
          key: AttributeKey.defending,
          detail: Detail.tackling,
          difficulty: 74,
          outcome: Outcome.play,
          successText: '思い切って足を伸ばし、ボールだけを突いた。',
          failureText: 'かわされ、2対0になった。',
        ),
        ScenarioOption(
          label: '遅らせて味方の戻りを待つ',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 58,
          outcome: Outcome.play,
          successText: '下がりながら時間を作り、味方が戻ってきた。',
          failureText: '下がりすぎて、シュートコースを与えた。',
        ),
        ScenarioOption(
          label: 'ファウルで止める',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 55,
          outcome: Outcome.play,
          successText: 'カードは出たが、決定的な場面を消した。',
          failureText: '倒しきれず、そのまま持ち運ばれた。',
        ),
      ],
    ),
    Scenario(
      id: 'df-longball',
      situation: '前線へ長いボール。相手FWと並んで落下点に入る。',
      options: [
        ScenarioOption(
          label: 'ヘディングで跳ね返す',
          key: AttributeKey.physical,
          detail: Detail.jumping,
          difficulty: 64,
          outcome: Outcome.play,
          successText: '高い打点で叩き、はるか前方へ跳ね返した。',
          failureText: '競り負け、背後に流された。',
        ),
        ScenarioOption(
          label: '胸で落として味方につなぐ',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 62,
          outcome: Outcome.play,
          successText: '柔らかく落とし、そこから組み立てが始まった。',
          failureText: '落とし所がずれ、拾われた。',
        ),
        ScenarioOption(
          label: '体を入れて先に触る',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 56,
          outcome: Outcome.play,
          successText: '先に体を入れ、相手を背負ったまま処理した。',
          failureText: '入れ替わられ、突破を許した。',
        ),
      ],
    ),
    Scenario(
      id: 'df-star',
      situation: '相手のエースに付く。背番号10が下がって受けたがっている。',
      options: [
        ScenarioOption(
          label: 'どこまでも付いていく',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 72,
          outcome: Outcome.play,
          successText: '前を向かせず、ボールを引き出す前に潰した。',
          failureText: '空けた背後を、別の選手に使われた。',
        ),
        ScenarioOption(
          label: '受け渡してコースを消す',
          key: AttributeKey.defending,
          detail: Detail.interceptions,
          difficulty: 63,
          outcome: Outcome.play,
          successText: '味方に受け渡し、縦のパスコースを消し切った。',
          failureText: '受け渡しが曖昧になり、間で受けられた。',
        ),
        ScenarioOption(
          label: '距離を取ってスペースを埋める',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 52,
          outcome: Outcome.play,
          successText: '危険な場所を先に埋め、何もさせなかった。',
          failureText: '自由に持たれ、決定的なパスを通された。',
        ),
      ],
    ),
    Scenario(
      id: 'df-scramble',
      situation: 'ゴール前の混戦。ボールがどこにあるか分からない。',
      options: [
        ScenarioOption(
          label: '思い切りクリアする',
          key: AttributeKey.physical,
          detail: Detail.strength,
          difficulty: 50,
          outcome: Outcome.play,
          successText: '当てるだけでいい。大きく蹴り出した。',
          failureText: '空振り。ボールは足元を抜けていった。',
        ),
        ScenarioOption(
          label: '足を伸ばしてつつく',
          key: AttributeKey.defending,
          detail: Detail.tackling,
          difficulty: 68,
          outcome: Outcome.play,
          successText: 'シュートの瞬間に爪先が届き、コースを変えた。',
          failureText: '足に当たらず、そのまま流し込まれた。',
        ),
        ScenarioOption(
          label: 'GKに預ける',
          key: AttributeKey.passing,
          detail: Detail.shortPassing,
          difficulty: 58,
          outcome: Outcome.play,
          successText: '落ち着いてGKへ。危険な時間が終わった。',
          failureText: '弱いバックパスを狙われた。',
        ),
      ],
    ),
    Scenario(
      id: 'df-penaltybox',
      situation: 'PA内で背後を取られた。足を出せばPKになる。',
      options: [
        ScenarioOption(
          label: '体を寄せて自由を奪う',
          key: AttributeKey.defending,
          detail: Detail.marking,
          difficulty: 70,
          outcome: Outcome.play,
          successText: '触れずに寄せ切り、苦し紛れのシュートに終わらせた。',
          failureText: '寄せ切れず、狙い澄まされた。',
        ),
        ScenarioOption(
          label: '足を出して止める',
          key: AttributeKey.defending,
          detail: Detail.tackling,
          difficulty: 77,
          outcome: Outcome.play,
          successText: '完璧なタイミング。ボールだけを大きく弾いた。',
          failureText: '足に掛かった。主審がスポットを指した。',
        ),
        ScenarioOption(
          label: 'コースだけ消して見送る',
          key: AttributeKey.defending,
          detail: Detail.interceptions,
          difficulty: 57,
          outcome: Outcome.play,
          successText: 'シュートコースに入り、体に当てて防いだ。',
          failureText: '中途半端な位置取りで、股を抜かれた。',
        ),
      ],
    ),
  ];
}
